# backend/memory.py
"""
Memory Module  ─  NovaCart AI
══════════════════════════════════════════════════════════
Two-layer memory architecture (mirrors AWS Bedrock memory):

┌─────────────────────────────────────────────────────┐
│  LAYER 1 — SHORT-TERM (within session)              │
│  Table: conversation_memory                         │
│  Sliding window of last 10 messages (5 turns)       │
│  Scoped per session_id                              │
│  Used by: all agents, router                        │
├─────────────────────────────────────────────────────┤
│  LAYER 2 — LONG-TERM (cross-session)               │
│  Table: session_summaries                           │
│  Compact structured summary of each past session   │
│  Scoped per user_id                                 │
│  Generated by LLM at session end                    │
│  Loaded at session start → injected into context   │
│  Enables: sentiment awareness, topic continuity,    │
│           recognising returning frustrated users    │
└─────────────────────────────────────────────────────┘
"""

import json
import sqlite3

from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from langchain_groq import ChatGroq
from dotenv import load_dotenv

load_dotenv()

MEMORY_DB         = "memory.db"
SHORT_TERM_WINDOW = 10    # 5 turns × 2 messages
MAX_SUMMARIES     = 5     # how many past session summaries to load per user

_summary_llm = None

def _get_summary_llm():
    global _summary_llm
    if _summary_llm is None:
        _summary_llm = ChatGroq(model="llama-3.1-8b-instant", temperature=0)
    return _summary_llm


# ─────────────────────────────────────────────────────────────────────
# INIT
# ─────────────────────────────────────────────────────────────────────

def init_memory_db():
    conn   = sqlite3.connect(MEMORY_DB)
    cursor = conn.cursor()

    # Layer 1 — Short-term per-session messages
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS conversation_memory (
            id         INTEGER  PRIMARY KEY AUTOINCREMENT,
            session_id TEXT     NOT NULL,
            role       TEXT     NOT NULL,
            content    TEXT     NOT NULL,
            timestamp  DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Layer 2 — Long-term per-user session summaries
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS session_summaries (
            id           INTEGER  PRIMARY KEY AUTOINCREMENT,
            user_id      TEXT     NOT NULL,
            session_id   TEXT     NOT NULL,
            summary      TEXT     NOT NULL,
            sentiment    TEXT     NOT NULL,
            topics       TEXT,
            unresolved   TEXT,
            created_at   DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    """)

    conn.commit()
    conn.close()


# ─────────────────────────────────────────────────────────────────────
# LAYER 1 — SHORT-TERM MEMORY
# ─────────────────────────────────────────────────────────────────────

def save_memory(session_id: str, messages: list):
    """Append messages to this session's conversation history."""
    if not messages:
        return
    conn   = sqlite3.connect(MEMORY_DB)
    cursor = conn.cursor()
    for msg in messages:
        role = "human" if isinstance(msg, HumanMessage) else "ai"
        cursor.execute(
            "INSERT INTO conversation_memory (session_id, role, content) VALUES (?, ?, ?)",
            (session_id, role, msg.content),
        )
    conn.commit()
    conn.close()


def load_memory(session_id: str, limit: int | None = SHORT_TERM_WINDOW) -> list:
    """
    Load conversation history for a session.
    limit=SHORT_TERM_WINDOW → recent context window (default)
    limit=None              → full history (used for summarization only)
    """
    conn   = sqlite3.connect(MEMORY_DB)
    cursor = conn.cursor()

    if limit:
        cursor.execute("""
            SELECT role, content
            FROM (
                SELECT id, role, content
                FROM   conversation_memory
                WHERE  session_id = ?
                ORDER  BY id DESC
                LIMIT  ?
            )
            ORDER BY id ASC
        """, (session_id, limit))
    else:
        cursor.execute("""
            SELECT role, content
            FROM   conversation_memory
            WHERE  session_id = ?
            ORDER  BY id ASC
        """, (session_id,))

    rows = cursor.fetchall()
    conn.close()

    result = []
    for role, content in rows:
        result.append(HumanMessage(content=content) if role == "human" else AIMessage(content=content))
    return result


def get_short_term_context(session_id: str) -> list:
    """
    Primary interface for all agents and the router.
    Returns the sliding short-term window for this session.
    """
    return load_memory(session_id, limit=SHORT_TERM_WINDOW)


# ─────────────────────────────────────────────────────────────────────
# LAYER 2 — LONG-TERM MEMORY  (session summarization)
# ─────────────────────────────────────────────────────────────────────

SUMMARIZATION_PROMPT = """\
You are a session summarizer for NovaCart, an e-commerce customer support AI.

Read the conversation below and produce a compact structured summary.

Your output must be ONLY valid JSON — no markdown, no explanation:
{
  "summary":    "<2-3 sentence natural language summary of what happened in this session>",
  "sentiment":  "<one of: positive | neutral | negative | frustrated>",
  "topics":     "<comma-separated list of topics: e.g. order_placement, order_tracking, returns, tickets, faq, escalation>",
  "unresolved": "<brief description of any issue that was NOT resolved, or null if everything was resolved>"
}

SENTIMENT GUIDE:
  positive   → user got what they wanted, conversation ended smoothly
  neutral    → informational session, no strong emotion
  negative   → user had a problem but it was handled adequately
  frustrated → user expressed frustration, anger, or requested human escalation

Be concise. The summary should be 2-3 sentences maximum.
The topics field should only list what actually came up in the conversation.
"""


def summarize_session(session_id: str, user_id: str) -> bool:
    """
    Generates a structured summary of a completed session and saves it.
    Called automatically by main.py when a new session starts (summarizing
    the previous session).

    Returns True if summary was saved, False if session had no messages
    or summarization failed.
    """
    # Load full conversation for this session
    history = load_memory(session_id, limit=None)

    if len(history) < 2:
        # Too short to be worth summarizing (e.g. user opened and closed immediately)
        return False

    # Check if already summarized
    conn   = sqlite3.connect(MEMORY_DB)
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id FROM session_summaries WHERE session_id = ?",
        (session_id,)
    )
    already_exists = cursor.fetchone()
    conn.close()

    if already_exists:
        return True  # already done

    # Build conversation text for the LLM
    convo_lines = []
    for msg in history:
        role = "User" if isinstance(msg, HumanMessage) else "Bot"
        convo_lines.append(f"{role}: {msg.content}")
    convo_text = "\n".join(convo_lines)

    # Call LLM to summarize
    try:
        llm      = _get_summary_llm()
        response = llm.invoke([
            SystemMessage(content=SUMMARIZATION_PROMPT),
            HumanMessage(content=f"Conversation to summarize:\n\n{convo_text}")
        ])
        raw    = response.content.strip()
        raw    = raw.replace("```json", "").replace("```", "").strip()
        result = json.loads(raw)

        summary    = result.get("summary", "Session completed.")
        sentiment  = result.get("sentiment", "neutral")
        topics     = result.get("topics", "")
        unresolved = result.get("unresolved")

    except Exception:
        # Fallback: save a minimal summary so the session isn't lost
        summary    = f"Session {session_id} completed. Could not generate detailed summary."
        sentiment  = "neutral"
        topics     = ""
        unresolved = None

    # Save to DB
    conn   = sqlite3.connect(MEMORY_DB)
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO session_summaries
            (user_id, session_id, summary, sentiment, topics, unresolved)
        VALUES (?, ?, ?, ?, ?, ?)
    """, (user_id, session_id, summary, sentiment, topics, unresolved))
    conn.commit()
    conn.close()

    return True


def load_user_summaries(user_id: str, limit: int = MAX_SUMMARIES) -> list:
    """
    Load the most recent N session summaries for a user.
    Returns a list of dicts: {summary, sentiment, topics, unresolved, created_at}
    """
    conn   = sqlite3.connect(MEMORY_DB)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT summary, sentiment, topics, unresolved, created_at
        FROM   session_summaries
        WHERE  user_id = ?
        ORDER  BY created_at DESC
        LIMIT  ?
    """, (user_id, limit))
    rows = cursor.fetchall()
    conn.close()

    return [
        {
            "summary":    row[0],
            "sentiment":  row[1],
            "topics":     row[2],
            "unresolved": row[3],
            "date":       (row[4] or "")[:10],
        }
        for row in reversed(rows)   # chronological order (oldest first)
    ]


def build_user_context_string(user_id: str) -> str | None:
    """
    Builds a compact string of past session summaries to inject into
    the router's system prompt as USER PROFILE context.

    Returns None if no past sessions exist yet.
    """
    summaries = load_user_summaries(user_id)

    if not summaries:
        return None

    lines = ["Past session summaries (oldest → most recent):"]
    for i, s in enumerate(summaries, 1):
        unresolved_part = f" ⚠️ Unresolved: {s['unresolved']}" if s["unresolved"] else ""
        lines.append(
            f"  {i}. [{s['date']}] [{s['sentiment'].upper()}] {s['summary']}"
            f"{unresolved_part}"
        )

    return "\n".join(lines)